language: php

branches:
    only:
        - master

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.1.14

env:
    - SYMFONY_VERSION="3.4.*" DB=sqlite

before-install:
    - composer self-update

install:
    - composer install
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - ./bin/console doctrine:database:create --env=test
    - ./bin/console doctrine:schema:create --env=test
    - ./bin/console doctrine:fixtures:load -n --env=test

script:
    - ./vendor/bin/simple-phpunit -v
    - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
    - ./bin/console lint:twig app/Resources
    - ./bin/console lint:yaml app/config
