language: php

branches:
    only:
        - master

dist: trusty
sudo: false

addons:
    mariadb: '10.2.8'

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 5.5.38
        - php: 5.6.31
        - php: 7.0.22
        - php: 7.1.8

env:
    - SYMFONY_VERSION="3.3.*" DB=mariadb

before-install:
    - composer self-update

install:
    - composer install
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:create

script:
    - ./vendor/bin/simple-phpunit -v
