language: php

sudo: false

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly

env:
    - SYMFONY_VERSION="3.3.*" DB=mysql

before-install:
    - composer self-update

install:
    - composer install
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    # - php bin/console doctrine:database:create
    # - php bin/console doctrine:schema:create
    # - php bin/console doctrine:fixtures:load -n --env=test

script:
    - ./vendor/bin/simple-phpunit -v
