<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTeamMembers()
    {
        $em = $this->getEntityManager();
        $dql = "SELECT u FROM AppBundle\Entity\User u
                WHERE u.job != 'NULL'
                ORDER BY u.date";
        $query = $em->createQuery($dql);
        return $query->execute();
    }
}
